apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-fast-food-api-deployment
  labels:
    app: tech-challenge-fast-food-api-deployment
spec:
  selector:
    matchLabels:
      app: tech-challenge-fast-food-api
  template:
    metadata:
      labels:
        app: tech-challenge-fast-food-api
    spec:
      containers:
        - name: tech-challenge-fast-food-api
          image: leosaglia/tech-challenge-fast-food-api
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_URL
            - name: PORT
              value: "3001"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
