apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-fast-food-postgres
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: tech-challenge-fast-food-postgres
  ports:
    - port: 5432
      targetPort: 5432