apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXNwYXNz
  POSTGRES_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzcGFzc0B0ZWNoLWNoYWxsZW5nZS1mYXN0LWZvb2QtcG9zdGdyZXM6NTQzMi90ZWNoY2hhbGxlbmdlLWZhc3Rmb29kP3NjaGVtYT1wdWJsaWM=
  POSTGRES_DB: dGVjaGNoYWxsZW5nZS1mYXN0Zm9vZA==
