on:
  push:
    branches:
      - main

jobs:
  deploy-to-dockerhub:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      DOCKERHUB_REPOSITORY: tech-challenge-fast-food-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build, tag, and push Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:latest .
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:latest
          